//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.DataAccess.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OrderSqls {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrderSqls() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OrderManagement.DataAccess.Properties.OrderSqls", typeof(OrderSqls).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM dbo.Orders 
        ///WHERE OrderId=&apos;@id&apos; and (OrderDate is null or ShippedDate is null);.
        /// </summary>
        internal static string DeleteSql {
            get {
                return ResourceManager.GetString("DeleteSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select  OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,ShipVia,Freight,ShipName,ShipAddress,ShipCity, ShipRegion,ShipPostalCode,ShipCountry,case     when OrderDate is null then 0        when ShippedDate is null then 1      else 2                           end as &apos;Status&apos;                      from dbo.Orders as Orders where OrderId = @id;
        ///select * from dbo.[Order Details] where OrderID = @id;.
        /// </summary>
        internal static string GetByIdSql {
            get {
                return ResourceManager.GetString("GetByIdSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select  OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,ShipVia,Freight,ShipName,ShipAddress,ShipCity, ShipRegion,ShipPostalCode,ShipCountry,case     when OrderDate is null then 0        when ShippedDate is null then 1      else 2                           end as &apos;Status&apos;                      from dbo.Orders as Orders;.
        /// </summary>
        internal static string GetCollectionSql {
            get {
                return ResourceManager.GetString("GetCollectionSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into dbo.Orders (CustomerID, EmployeeID, RequiredDate, ShipVia, Freight, ShipName, ShipAddress, ShipCity, ShipRegion, ShipPostalCode, ShipCountry)
        ///values (&apos;@custId&apos;, &apos;@emplId&apos;, &apos;@reqDate&apos;, &apos;@shipVia&apos;, &apos;@freight&apos;, &apos;@shipName&apos;, &apos;@shipAddress&apos;, &apos;@shipCity&apos;, &apos;shipRegion&apos;, &apos;@shipPostalCode&apos;, &apos;@shipCntry&apos;).
        /// </summary>
        internal static string InsertSql {
            get {
                return ResourceManager.GetString("InsertSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update [dbo].[Orders] set ShippedDate=&apos;@dateTime&apos; where OrderId=&apos;@id&apos; and ShippedDate is null;.
        /// </summary>
        internal static string MarkAsDone {
            get {
                return ResourceManager.GetString("MarkAsDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update [dbo].[Orders] set OrderDate=&apos;@dateTime&apos; where OrderId=&apos;@id&apos; and OrderDate is null;.
        /// </summary>
        internal static string MoveToProgress {
            get {
                return ResourceManager.GetString("MoveToProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [dbo].[Orders]
        ///   SET [CustomerID] = &apos;@custId&apos;
        ///      ,[EmployeeID] = &apos;@emplId&apos;
        ///      ,[RequiredDate] = &apos;@reqDate&apos;
        ///      ,[ShipVia] = &apos;@shipVia&apos;
        ///      ,[Freight] = &apos;@freight&apos;
        ///      ,[ShipName] = &apos;@shipName&apos;
        ///      ,[ShipAddress] = &apos;@shipAddress&apos;
        ///      ,[ShipCity] = &apos;@shipCity&apos;
        ///      ,[ShipRegion] = &apos;@shipRegion&apos;
        ///      ,[ShipPostalCode] = &apos;@shipPostalCode&apos;
        ///      ,[ShipCountry] = &apos;@shipCntry&apos;
        ///WHERE OrderId=&apos;@orderId&apos;.
        /// </summary>
        internal static string UpdateSql {
            get {
                return ResourceManager.GetString("UpdateSql", resourceCulture);
            }
        }
    }
}
